default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: test_deploy_development_neversmile

test:
  <<: *default
  database: test_deploy_test_neversmile

production:
  <<: *default
  database: test_deploy_production
  username: faq
  password: <%= ENV["FAQ_DATABASE_PASSWORD"] %>